### ISSUE TITLE
A user should only be able to vote once on a contest

### ISSUE THREAD

**Issue by Tobitron** [MatthewRiggott/Best-Picture#6]
Currently you can vote as many times as you want.

**Comment by MatthewRiggott** [comment]
Add a votes table containing the contest id, user id, and photo id.  Then put unique index on contest within the scope of user.

**Comment by Tobitron** [comment]
Sounds like we have a volunteer!

**Comment by Tobitron** [comment]
Thanks Matt, working nicely. Note the current behavior is that if a user tries to vote on a contest twice they are automatically redirected to a different contest and shown a flash message stating that they can't vote on the same contest twice. Maybe it's more elegant to show them a JS popup or something or a flash message on that page but this was easier and seems productive to automatically bring them to a new contest.
